### PR TITLE
Repository re-structured.

### PR DESCRIPTION
**Pull request by Purvanshsingh**
I have restructured the repository, All the other modifications will be done over this PR once this is merged.

- doc_writer file & APIDoc are in the **API_Doc** folder ( Saving API_Doc in the proper format will be done in a separate PR)
- NonPerformingLoan vocabulary present in **NPL_vocab** folder
- requirement.txt file added.
- setup.py file added.
- main.py renamed
- config file added. ( for fetching DB_URL & API_Doc path)

All the other modifications mentioned in #3 will be done in a separate PR over this structure.

### CODE REVIEW

**Comment by chrizandr** [comment]
These changes seem to be incremental to #3 . I see just one new commit, why has this been added to a separate PR?

**Comment by Purvanshsingh** [comment]
There were other changes too in #3, but I wanted to be sure with this structure. that's why open a separate PR.

**Comment by chrizandr** [comment]
Yes the structure looks good to me. Let's not have multiple PRs having reduntant content, I think you can just add that commit to #3. PRs should just contain commits related to a single issue, makes it easier to review.

**Comment by Purvanshsingh** [comment]
@chrizandr ok, will create the commit in the same PR.

**Pull request closed without merging**
